criterion:
  classes_per_batch: 10
  me_max: true
  sharpen: 0.25
  supervised_imgs_per_class: 5
  supervised_views: 2
  temperature: 0.1
  unsupervised_batch_size: 256
  unlabeled_supervised_imgs_per_class: 3
data:
  color_jitter_strength: 0.5
  data_seed: 0
  dataset: cifar10
  image_folder: cifar10/
  label_smoothing: 0.1
  multicrop: 2
  us_multicrop: 2
  normalize: true
  root_path: datasets/
  subset_path: subsets/cifar10/5%_seed0.txt
  subset_path_cls: subsets/cifar10/5%_seed0_cls.txt
  unique_classes_per_rank: false
  unlabeled_frac: 0.92
logging:
  folder: experiments/cifar10-5%
  write_tag: nncsl
  wandb: false
meta:
  copy_data: false
  device: cuda:0
  load_checkpoint: false
  save_checkpoint: true
  start_task_idx: 0
  model_name: resnet18
  output_dim: 128
  read_checkpoint: null
  use_fp16: true
  use_pred_head: false
  name: c10-r18-5%-buffer500-nncsl
  w_paws: 1
  w_me_max: 1
  w_online: 0.005
  w_dist: 0.2
  w_dist_more: 0
  alpha: 0
optimization:
  epochs: 250
  start_lr: 0.08
  lr: 0.4
  final_lr: 0.032
  lr_cls: 0.12
  momentum: 0.9
  nesterov: false
  warmup: 10
  weight_decay: 1.0e-05
continual:
  num_tasks: 5
  setting: current
  mask: true
  buffer_size: 500
  detach: false