criterion:
  classes_per_batch: 15
  me_max: true
  sharpen: 0.25
  supervised_imgs_per_class: 3
  supervised_views: 2
  temperature: 0.1
  unsupervised_batch_size: 64
  unlabeled_supervised_imgs_per_class: 2
data:
  color_jitter_strength: 1.0
  data_seed: 152
  dataset: imagenet
  image_folder: imagenet100/
  label_smoothing: 0.1
  multicrop: 2
  us_multicrop: 2
  normalize: true
  root_path: datasets/
  subset_path: ./subsets/imagenet100/1%_seed0.txt
  subset_path_cls: ./subsets/imagenet100/1%_seed0_cls.txt
  unique_classes_per_rank: true
  unlabeled_frac: 0.9
logging:
  folder: ./experiments/imgnt100-1%
  write_tag: nncsl
  wandb: false
meta:
  copy_data: false
  device: cuda:0
  load_checkpoint: false
  save_checkpoint: true
  start_task_idx: 0
  model_name: resnet18
  output_dim: 128
  read_checkpoint: null
  use_fp16: false
  use_pred_head: false
  name: nncsl-imgnt100-r18-1%-20T-current-no_mask-sup5-lr1.2-epoch100-detach-clf.12-online.005-wd5-buffer500
  w_paws: 1
  w_me_max: 1
  w_online: 0.005
  w_dist: 0
  w_dist_more: 0
  alpha: 0
optimization:
  epochs: 100
  final_lr: 0.064
  lr_cls: 0.12
  lr: 1.2
  momentum: 0.9
  nesterov: false
  start_lr: 0.3
  warmup: 10
  weight_decay: 1.0e-05
continual:
  num_tasks: 20
  setting: current
  mask: false
  buffer_size: 500
  detach: true